### PR TITLE
created news-feed img folder, created news-feed page

### PR DESCRIPTION
**Pull request by keishacard**
keisha's branch and img

### CODE REVIEW

**Review by hcleland — COMMENTED** [review]
Text is all there!  Just need the images.

**Comment by keishacard** [comment]
updated with imgs!

**Review by dek-haji — APPROVED** [review]

**Comment by hcleland** [comment]
👍 Looks good!

**Comment by jasoncollum** [comment]
👍

**Review by jasoncollum — COMMENTED** [review]
👍

**Pull request merged**
